//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayMagnifyRes.c"
#include "UIFlowWndPlayMagnify.h"
#include "PrjCfg.h"

//---------------------UIFlowWndPlayMagnifyCtrl Debug Definition -----------------------------
#define _UIFLOWWNDPLAYMAGNIFY_ERROR_MSG        1
#define _UIFLOWWNDPLAYMAGNIFY_TRACE_MSG        0

#if (_UIFLOWWNDPLAYMAGNIFY_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndPlayMagnifyErrMsg(...)            debug_msg ("^R UIFlowWndPlayMagnify: "__VA_ARGS__)
#else
#define UIFlowWndPlayMagnifyErrMsg(...)
#endif

#if (_UIFLOWWNDPLAYMAGNIFY_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndPlayMagnifyTraceMsg(...)          debug_msg ("^B UIFlowWndPlayMagnify: "__VA_ARGS__)
#else
#define UIFlowWndPlayMagnifyTraceMsg(...)
#endif

//---------------------UIFlowWndPlayMagnifyCtrl Global Variables -----------------------------

//---------------------UIFlowWndPlayMagnifyCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndPlayMagnifyCtrl Public API  ----------------------------------

//---------------------UIFlowWndPlayMagnifyCtrl Private API  ---------------------------------
//---------------------UIFlowWndPlayMagnifyCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlayMagnify)
CTRL_LIST_ITEM(UIFlowWndPlayMagnify_StaticTXT_DZoom)
CTRL_LIST_ITEM(UIFlowWndPlayMagnify_StaticIcon_DirUp)
CTRL_LIST_ITEM(UIFlowWndPlayMagnify_StaticIcon_DirDown)
CTRL_LIST_ITEM(UIFlowWndPlayMagnify_StaticIcon_DirRight)
CTRL_LIST_ITEM(UIFlowWndPlayMagnify_StaticIcon_DirLeft)
CTRL_LIST_END

//----------------------UIFlowWndPlayMagnifyCtrl Event---------------------------
INT32 UIFlowWndPlayMagnify_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlayMagnify_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlayMagnify)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlayMagnify_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlayMagnify_OnClose)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIFlowWndPlayMagnify_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIFlowWndPlayMagnify_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndPlayMagnify_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndPlayMagnify_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndPlayMagnify_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlayMagnify_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndPlayMagnify_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndPlayMagnify_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndPlayMagnify_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndPlayMagnify_OnKeyShutter2)
EVENT_END

INT32 UIFlowWndPlayMagnify_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlayMagnify_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlayMagnify_StaticTXT_DZoomCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayMagnify_StaticTXT_DZoom)
EVENT_END

//----------------------UIFlowWndPlayMagnify_StaticIcon_DirUpCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayMagnify_StaticIcon_DirUp)
EVENT_END

//----------------------UIFlowWndPlayMagnify_StaticIcon_DirDownCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayMagnify_StaticIcon_DirDown)
EVENT_END

//----------------------UIFlowWndPlayMagnify_StaticIcon_DirRightCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayMagnify_StaticIcon_DirRight)
EVENT_END

//----------------------UIFlowWndPlayMagnify_StaticIcon_DirLeftCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlayMagnify_StaticIcon_DirLeft)
EVENT_END

