//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoWBRes.c"
#include "UIMenuWndPhotoWB.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPhotoWBCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOWB_ERROR_MSG        1
#define _UIMENUWNDPHOTOWB_TRACE_MSG        0

#if (_UIMENUWNDPHOTOWB_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoWBErrMsg(...)            debug_msg ("^R UIMenuWndPhotoWB: "__VA_ARGS__)
#else
#define UIMenuWndPhotoWBErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOWB_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoWBTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoWB: "__VA_ARGS__)
#else
#define UIMenuWndPhotoWBTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoWBCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoWBCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoWBCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoWBCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoWBCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoWB)
CTRL_LIST_ITEM(UIMenuWndPhotoWB_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPhotoWBCtrl Event---------------------------
INT32 UIMenuWndPhotoWB_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoWB)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoWB_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoWB_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoWB_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoWB_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoWB_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPhotoWB_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPhotoWB_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoWB_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoWB_Panel)
CTRL_LIST_ITEM(UIMenuWndPhotoWB_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoWB_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoWB_Panel)
EVENT_END

//----------------------UIMenuWndPhotoWB_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoWB_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoWB_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoWB_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoWB_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoWB_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoWB_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoWB_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoWB_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
