//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoExposureRes.c"
#include "UIMenuWndPhotoExposure.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPhotoExposureCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOEXPOSURE_ERROR_MSG        1
#define _UIMENUWNDPHOTOEXPOSURE_TRACE_MSG        0

#if (_UIMENUWNDPHOTOEXPOSURE_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoExposureErrMsg(...)            debug_msg ("^R UIMenuWndPhotoExposure: "__VA_ARGS__)
#else
#define UIMenuWndPhotoExposureErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOEXPOSURE_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoExposureTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoExposure: "__VA_ARGS__)
#else
#define UIMenuWndPhotoExposureTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoExposureCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoExposureCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoExposureCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoExposureCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoExposureCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoExposure)
CTRL_LIST_ITEM(UIMenuWndPhotoExposure_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPhotoExposureCtrl Event---------------------------
INT32 UIMenuWndPhotoExposure_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoExposure)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoExposure_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoExposure_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoExposure_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoExposure_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoExposure_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPhotoExposure_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPhotoExposure_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoExposure_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoExposure_Panel)
CTRL_LIST_ITEM(UIMenuWndPhotoExposure_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoExposure_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoExposure_Panel)
EVENT_END

//----------------------UIMenuWndPhotoExposure_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoExposure_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoExposure_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoExposure_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoExposure_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoExposure_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoExposure_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoExposure_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoExposure_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
