//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPhotoColorRes.c"
#include "UIMenuWndPhotoColor.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPhotoColorCtrl Debug Definition -----------------------------
#define _UIMENUWNDPHOTOCOLOR_ERROR_MSG        1
#define _UIMENUWNDPHOTOCOLOR_TRACE_MSG        0

#if (_UIMENUWNDPHOTOCOLOR_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPhotoColorErrMsg(...)            debug_msg ("^R UIMenuWndPhotoColor: "__VA_ARGS__)
#else
#define UIMenuWndPhotoColorErrMsg(...)
#endif

#if (_UIMENUWNDPHOTOCOLOR_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPhotoColorTraceMsg(...)          debug_msg ("^B UIMenuWndPhotoColor: "__VA_ARGS__)
#else
#define UIMenuWndPhotoColorTraceMsg(...)
#endif

//---------------------UIMenuWndPhotoColorCtrl Global Variables -----------------------------

//---------------------UIMenuWndPhotoColorCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPhotoColorCtrl Public API  ----------------------------------

//---------------------UIMenuWndPhotoColorCtrl Private API  ---------------------------------
//---------------------UIMenuWndPhotoColorCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoColor)
CTRL_LIST_ITEM(UIMenuWndPhotoColor_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPhotoColorCtrl Event---------------------------
INT32 UIMenuWndPhotoColor_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoColor)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPhotoColor_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPhotoColor_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPhotoColor_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPhotoColor_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPhotoColor_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPhotoColor_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPhotoColor_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPhotoColor_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPhotoColor_Panel)
CTRL_LIST_ITEM(UIMenuWndPhotoColor_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPhotoColor_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPhotoColor_Panel)
EVENT_END

//----------------------UIMenuWndPhotoColor_MenuCtrl Event---------------------------
INT32 UIMenuWndPhotoColor_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPhotoColor_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPhotoColor_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPhotoColor_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPhotoColor_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPhotoColor_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPhotoColor_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPhotoColor_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
