//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDAIR_WARING_H
#define UIFLOWWNDAIR_WARING_H

#include "UIFramework.h"

extern VControl UIFlowWndAIR_WaringCtrl;//Panel type 

extern VControl UIFlowWndAIR_Waring_panelCtrl;//Panel type 

extern VControl UIFlowWndAIR_Quility_titleCtrl;//Static type 

extern VControl UIFlowWndAIR_Quility_valueCtrl;//Static type 

extern VControl UIFlowWndAIR_Fresh_titleCtrl;//Static type 

extern VControl UIFlowWndAIR_Fresh_valueCtrl;//Static type 

extern VControl UIFlowWndAIR_PW25Ctrl;//Static type 

extern VControl UIFlowWndAIR_PW25_valueCtrl;//Static type 

//---------------------UIFlowWndAIR_WaringCtrl User Export---------------------------
#endif
