//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintSettingRes.c"
#include "UIMenuWndPrint_PrintSetting.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_PrintSettingCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_PRINTSETTING_ERROR_MSG        1
#define _UIMENUWNDPRINT_PRINTSETTING_TRACE_MSG        0

#if (_UIMENUWNDPRINT_PRINTSETTING_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_PrintSettingErrMsg(...)            debug_msg ("^R UIMenuWndPrint_PrintSetting: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintSettingErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_PRINTSETTING_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_PrintSettingTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_PrintSetting: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintSettingTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_PrintSettingCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_PrintSettingCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_PrintSettingCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_PrintSettingCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_PrintSettingCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Quality_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_PaperType_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_PaperSize_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_DatePrint_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_FilenamePrint_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Layout_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_FixedSize_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSettingCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintSetting_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintSetting)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintSetting_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintSetting_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintSetting_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_PrintSetting_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_PrintSetting_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintSetting_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_Dir_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_Dir_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_End_Dir2_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_End_Dir2_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Menu_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintSetting_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintSetting_Quality_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Quality_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_PaperType_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_PaperType_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_PaperSize_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_PaperSize_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_DatePrint_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_DatePrint_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_FilenamePrint_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_FilenamePrint_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_ImageOptimizes_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_ImageOptimizes_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_Layout_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Layout_Menu)
EVENT_END

//----------------------UIMenuWndPrint_PrintSetting_FixedSize_MenuCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_FixedSize_Menu)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Dir_Left_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Dir_Left_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintSetting_Dir_Right_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintSetting_Dir_Right_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintSetting_Dir_Right_Panel)
EVENT_END

