//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDPRINT_CROP_H
#define UIMENUWNDPRINT_CROP_H

#include "UIFramework.h"

extern VControl UIMenuWndPrint_CropCtrl;//Panel type 

extern VControl UIMenuWndPrint_Crop_Title_Text_StatusCtrl;//Status type 

typedef enum
{
UIMenuWndPrint_Crop_Title_Text_Status_STRID_CROP,
UIMenuWndPrint_Crop_Title_Text_Status_MAX
}UIMenuWndPrint_Crop_Title_Text_Status_Setting;

extern VControl UIMenuWndPrint_Crop_End_Dir_Menu_PanelCtrl;//Panel type 

//---------------------UIMenuWndPrint_CropCtrl User Export---------------------------
#endif
