//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrintRes.c"
#include "UIMenuWndPrint.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrintCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_ERROR_MSG        1
#define _UIMENUWNDPRINT_TRACE_MSG        0

#if (_UIMENUWNDPRINT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrintErrMsg(...)            debug_msg ("^R UIMenuWndPrint: "__VA_ARGS__)
#else
#define UIMenuWndPrintErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrintTraceMsg(...)          debug_msg ("^B UIMenuWndPrint: "__VA_ARGS__)
#else
#define UIMenuWndPrintTraceMsg(...)
#endif

//---------------------UIMenuWndPrintCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrintCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrintCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrintCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrintCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint)
CTRL_LIST_ITEM(UIMenuWndPrint_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Menu_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPrintCtrl Event---------------------------
INT32 UIMenuWndPrint_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPrint_OnChildClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_OnPrintDpsEvent)
EVENT_END

INT32 UIMenuWndPrint_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_End_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_End_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Menu_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
