//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_ConfirmRes.c"
#include "UIMenuWndPrint_Confirm.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_ConfirmCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_CONFIRM_ERROR_MSG        1
#define _UIMENUWNDPRINT_CONFIRM_TRACE_MSG        0

#if (_UIMENUWNDPRINT_CONFIRM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_ConfirmErrMsg(...)            debug_msg ("^R UIMenuWndPrint_Confirm: "__VA_ARGS__)
#else
#define UIMenuWndPrint_ConfirmErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_CONFIRM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_ConfirmTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_Confirm: "__VA_ARGS__)
#else
#define UIMenuWndPrint_ConfirmTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_ConfirmCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_ConfirmCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_ConfirmCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_ConfirmCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_ConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Confirm_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Text_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_ConfirmCtrl Event---------------------------
INT32 UIMenuWndPrint_Confirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Confirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_Confirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_Confirm_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_Confirm_OnPrintDpsEvent)
EVENT_END

INT32 UIMenuWndPrint_Confirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_Confirm_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_Confirm_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_Confirm_End_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_Confirm_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_Confirm_End_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_Confirm_Confirm_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_Confirm_Confirm_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_Confirm_Confirm_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_Confirm_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_Confirm_Text_Status)
EVENT_END

