//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintProgressRes.c"
#include "UIMenuWndPrint_PrintProgress.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_PrintProgressCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_PRINTPROGRESS_ERROR_MSG        1
#define _UIMENUWNDPRINT_PRINTPROGRESS_TRACE_MSG        0

#if (_UIMENUWNDPRINT_PRINTPROGRESS_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_PrintProgressErrMsg(...)            debug_msg ("^R UIMenuWndPrint_PrintProgress: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintProgressErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_PRINTPROGRESS_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_PrintProgressTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_PrintProgress: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintProgressTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_PrintProgressCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_PrintProgressCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_PrintProgressCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_PrintProgressCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_PrintProgressCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Confirm_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Status_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Progress_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgressCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintProgress_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintProgress)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintProgress_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintProgress_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintProgress_OnPrintDpsEvent)
EVENT_END

INT32 UIMenuWndPrint_PrintProgress_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintProgress_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintProgress_End_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintProgress_End_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Confirm_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Confirm_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintProgress_Confirm_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintProgress_Status_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Status_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintProgress_Progress_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintProgress_Progress_Status)
EVENT_END

