//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_SelectImagesRes.c"
#include "UIMenuWndPrint_SelectImages.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_SelectImagesCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_SELECTIMAGES_ERROR_MSG        1
#define _UIMENUWNDPRINT_SELECTIMAGES_TRACE_MSG        0

#if (_UIMENUWNDPRINT_SELECTIMAGES_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_SelectImagesErrMsg(...)            debug_msg ("^R UIMenuWndPrint_SelectImages: "__VA_ARGS__)
#else
#define UIMenuWndPrint_SelectImagesErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_SELECTIMAGES_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_SelectImagesTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_SelectImages: "__VA_ARGS__)
#else
#define UIMenuWndPrint_SelectImagesTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_SelectImagesCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_SelectImagesCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_SelectImagesCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_SelectImagesCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_SelectImagesCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Images_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Copy_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImagesCtrl Event---------------------------
INT32 UIMenuWndPrint_SelectImages_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_SelectImages)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_SelectImages_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_SelectImages_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_SelectImages_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_SelectImages_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_SelectImages_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_SelectImages_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_Dir_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_Dir_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_End_Dir2_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_End_Dir2_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Menu_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_SelectImages_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_SelectImages_Images_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Images_Status)
EVENT_END

//----------------------UIMenuWndPrint_SelectImages_Copy_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Copy_Status)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Dir_Left_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Dir_Left_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_SelectImages_Dir_Right_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_SelectImages_Dir_Right_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_SelectImages_Dir_Right_Panel)
EVENT_END

