//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintAllRes.c"
#include "UIMenuWndPrint_PrintAll.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_PrintAllCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_PRINTALL_ERROR_MSG        1
#define _UIMENUWNDPRINT_PRINTALL_TRACE_MSG        0

#if (_UIMENUWNDPRINT_PRINTALL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_PrintAllErrMsg(...)            debug_msg ("^R UIMenuWndPrint_PrintAll: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintAllErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_PRINTALL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_PrintAllTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_PrintAll: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintAllTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_PrintAllCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_PrintAllCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_PrintAllCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_PrintAllCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_PrintAllCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Menu_Menu)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Copy_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAllCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintAll_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintAll)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintAll_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintAll_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintAll_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_PrintAll_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_PrintAll_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintAll_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_Dir_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_Dir_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Dir_Menu_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_End_Dir2_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_End_Dir2_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_End_Dir2_Menu_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintAll_Menu_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintAll_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPrint_PrintAll_Copy_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Copy_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Dir_Left_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Dir_Left_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Dir_Left_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintAll_Dir_Right_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintAll_Dir_Right_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintAll_Dir_Right_Panel)
EVENT_END

