//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPrint_PrintDPOFRes.c"
#include "UIMenuWndPrint_PrintDPOF.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPrint_PrintDPOFCtrl Debug Definition -----------------------------
#define _UIMENUWNDPRINT_PRINTDPOF_ERROR_MSG        1
#define _UIMENUWNDPRINT_PRINTDPOF_TRACE_MSG        0

#if (_UIMENUWNDPRINT_PRINTDPOF_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPrint_PrintDPOFErrMsg(...)            debug_msg ("^R UIMenuWndPrint_PrintDPOF: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintDPOFErrMsg(...)
#endif

#if (_UIMENUWNDPRINT_PRINTDPOF_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPrint_PrintDPOFTraceMsg(...)          debug_msg ("^B UIMenuWndPrint_PrintDPOF: "__VA_ARGS__)
#else
#define UIMenuWndPrint_PrintDPOFTraceMsg(...)
#endif

//---------------------UIMenuWndPrint_PrintDPOFCtrl Global Variables -----------------------------

//---------------------UIMenuWndPrint_PrintDPOFCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPrint_PrintDPOFCtrl Public API  ----------------------------------

//---------------------UIMenuWndPrint_PrintDPOFCtrl Private API  ---------------------------------
//---------------------UIMenuWndPrint_PrintDPOFCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintDPOF)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_Content_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_Menu_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintDPOFCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintDPOF_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPrint_PrintDPOF_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPrint_PrintDPOF_OnClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIMenuWndPrint_PrintDPOF_OnPrintDpsEvent)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPrint_PrintDPOF_OnKeyMenu)
EVENT_END

INT32 UIMenuWndPrint_PrintDPOF_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPrint_PrintDPOF_Content_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintDPOF_Content_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintDPOF_Content_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_Content_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintDPOF_Title_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintDPOF_Title_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_Title_Text_Status)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_Title_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintDPOF_Title_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_Title_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintDPOF_Title_Text_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_Title_Text_Status)
EVENT_END

//----------------------UIMenuWndPrint_PrintDPOF_Title_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_Title_Icon_Status)
EVENT_END

//---------------------UIMenuWndPrint_PrintDPOF_End_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintDPOF_End_Panel)
CTRL_LIST_ITEM(UIMenuWndPrint_PrintDPOF_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintDPOF_End_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_End_Panel)
EVENT_END

//---------------------UIMenuWndPrint_PrintDPOF_End_Dir_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPrint_PrintDPOF_End_Dir_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPrint_PrintDPOF_End_Dir_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_End_Dir_Panel)
EVENT_END

//----------------------UIMenuWndPrint_PrintDPOF_Menu_MenuCtrl Event---------------------------
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPrint_PrintDPOF_Menu_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPrint_PrintDPOF_Menu_Menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
