//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndMP3Res.c"
#include "UIFlowWndMP3.h"
#include "PrjCfg.h"

//---------------------UIFlowWndMP3Ctrl Debug Definition -----------------------------
#define _UIFLOWWNDMP3_ERROR_MSG        1
#define _UIFLOWWNDMP3_TRACE_MSG        0

#if (_UIFLOWWNDMP3_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndMP3ErrMsg(...)            debug_msg ("^R UIFlowWndMP3: "__VA_ARGS__)
#else
#define UIFlowWndMP3ErrMsg(...)
#endif

#if (_UIFLOWWNDMP3_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndMP3TraceMsg(...)          debug_msg ("^B UIFlowWndMP3: "__VA_ARGS__)
#else
#define UIFlowWndMP3TraceMsg(...)
#endif

//---------------------UIFlowWndMP3Ctrl Global Variables -----------------------------

//---------------------UIFlowWndMP3Ctrl Prototype Declaration  -----------------------

//---------------------UIFlowWndMP3Ctrl Public API  ----------------------------------

//---------------------UIFlowWndMP3Ctrl Private API  ---------------------------------
//---------------------UIFlowWndMP3Ctrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndMP3)
CTRL_LIST_ITEM(MP3_TitleBar)
CTRL_LIST_ITEM(MP3_Main_Background)
CTRL_LIST_ITEM(MP3_Main_Menu)
CTRL_LIST_ITEM(MP3_Menu_ScrollBar)
CTRL_LIST_ITEM(MP3_Menu_Panel)
CTRL_LIST_ITEM(MP3_Menu_RunPanel)
CTRL_LIST_ITEM(MP3_TipsBar)
CTRL_LIST_ITEM(MP3_Icon_OK)
CTRL_LIST_ITEM(MP3_Text_Play)
CTRL_LIST_ITEM(MP3_Text_SelectNum)
CTRL_LIST_ITEM(MP3_Icon_Battery)
CTRL_LIST_END

//----------------------UIFlowWndMP3Ctrl Event---------------------------
INT32 UIFlowWndMP3_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndMP3_OnBattery(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndMP3)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndMP3_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndMP3_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndMP3_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndMP3_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndMP3_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndMP3_OnKeyPlayback)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIFlowWndMP3_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndMP3_OnStorageChange)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndMP3_OnBattery)
EVENT_END

INT32 UIFlowWndMP3_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_MENU,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_MODE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_PLAYBACK,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_STORAGE_INIT,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_STORAGE_CHANGE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndMP3_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_BATTERY,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------MP3_TitleBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MP3_TitleBar)
CTRL_LIST_ITEM(MP3_Text_PlayTime)
CTRL_LIST_ITEM(MP3_Text_MP3Mode)
CTRL_LIST_END

//----------------------MP3_TitleBarCtrl Event---------------------------
EVENT_BEGIN(MP3_TitleBar)
EVENT_END

//----------------------MP3_Text_PlayTimeCtrl Event---------------------------
EVENT_BEGIN(MP3_Text_PlayTime)
EVENT_END

//----------------------MP3_Text_MP3ModeCtrl Event---------------------------
EVENT_BEGIN(MP3_Text_MP3Mode)
EVENT_END

//---------------------MP3_Main_BackgroundCtrl Control List---------------------------
CTRL_LIST_BEGIN(MP3_Main_Background)
CTRL_LIST_END

//----------------------MP3_Main_BackgroundCtrl Event---------------------------
EVENT_BEGIN(MP3_Main_Background)
EVENT_END

//----------------------MP3_Main_MenuCtrl Event---------------------------
INT32 MP3_Main_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 MP3_Main_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 MP3_Main_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 MP3_Main_Menu_OnTimer(VControl *, UINT32, UINT32 *);
INT32 (VControl *, UINT32, UINT32 *);
INT32 (VControl *, UINT32, UINT32 *);
EVENT_BEGIN(MP3_Main_Menu)
EVENT_ITEM(NVTEVT_KEY_DOWN,MP3_Main_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_UP,MP3_Main_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_ENTER,MP3_Main_Menu_OnKeyEnter)
EVENT_ITEM(NVTEVT_TIMER,MP3_Main_Menu_OnTimer)
EVENT_ITEM(NVTEVT_CB_MP3PLAY_ONESECOND,)
EVENT_ITEM(NVTEVT_CB_MP3PLAY_FINISH,)
EVENT_END

INT32 MP3_Main_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MP3_Main_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 MP3_Main_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_ENTER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 MP3_Main_Menu_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 (VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CB_MP3PLAY_ONESECOND,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 (VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CB_MP3PLAY_FINISH,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------MP3_Menu_ScrollBarCtrl Event---------------------------
EVENT_BEGIN(MP3_Menu_ScrollBar)
EVENT_END

//---------------------MP3_Menu_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MP3_Menu_Panel)
CTRL_LIST_END

//----------------------MP3_Menu_PanelCtrl Event---------------------------
EVENT_BEGIN(MP3_Menu_Panel)
EVENT_END

//---------------------MP3_Menu_RunPanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(MP3_Menu_RunPanel)
CTRL_LIST_ITEM(MP3_Text_Song)
CTRL_LIST_END

//----------------------MP3_Menu_RunPanelCtrl Event---------------------------
EVENT_BEGIN(MP3_Menu_RunPanel)
EVENT_END

//----------------------MP3_Text_SongCtrl Event---------------------------
EVENT_BEGIN(MP3_Text_Song)
EVENT_END

//---------------------MP3_TipsBarCtrl Control List---------------------------
CTRL_LIST_BEGIN(MP3_TipsBar)
CTRL_LIST_END

//----------------------MP3_TipsBarCtrl Event---------------------------
EVENT_BEGIN(MP3_TipsBar)
EVENT_END

//----------------------MP3_Icon_OKCtrl Event---------------------------
EVENT_BEGIN(MP3_Icon_OK)
EVENT_END

//----------------------MP3_Text_PlayCtrl Event---------------------------
EVENT_BEGIN(MP3_Text_Play)
EVENT_END

//----------------------MP3_Text_SelectNumCtrl Event---------------------------
EVENT_BEGIN(MP3_Text_SelectNum)
EVENT_END

//----------------------MP3_Icon_BatteryCtrl Event---------------------------
EVENT_BEGIN(MP3_Icon_Battery)
EVENT_END

