//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiWaitRes.c"
#include "UIMenuWndWiFiWait.h"
#include "PrjCfg.h"

//---------------------UIMenuWndWiFiWaitCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIWAIT_ERROR_MSG        1
#define _UIMENUWNDWIFIWAIT_TRACE_MSG        0

#if (_UIMENUWNDWIFIWAIT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiWaitErrMsg(...)            debug_msg ("^R UIMenuWndWiFiWait: "__VA_ARGS__)
#else
#define UIMenuWndWiFiWaitErrMsg(...)
#endif

#if (_UIMENUWNDWIFIWAIT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiWaitTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiWait: "__VA_ARGS__)
#else
#define UIMenuWndWiFiWaitTraceMsg(...)
#endif

//---------------------UIMenuWndWiFiWaitCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiWaitCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiWaitCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiWaitCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiWaitCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiWait)
CTRL_LIST_ITEM(UIMenuWndWiFiWait_Connect_Icon_Status)
CTRL_LIST_END

//----------------------UIMenuWndWiFiWaitCtrl Event---------------------------
INT32 UIMenuWndWiFiWait_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiWait_OnBackgroundDone(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiWait)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndWiFiWait_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndWiFiWait_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndWiFiWait_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndWiFiWait_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndWiFiWait_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndWiFiWait_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndWiFiWait_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndWiFiWait_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndWiFiWait_OnKeyMode)
EVENT_ITEM(NVTEVT_BATTERY,UIMenuWndWiFiWait_OnBattery)
EVENT_ITEM(NVTEVT_TIMER,UIMenuWndWiFiWait_OnTimer)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE,UIMenuWndWiFiWait_OnBackgroundDone)
EVENT_END

INT32 UIMenuWndWiFiWait_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_MENU,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_UP,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_DOWN,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_ENTER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_KEY_SHUTTER2,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_TIMER,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiWait_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiWait_Connect_Icon_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiWait_Connect_Icon_Status)
EVENT_END

