//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDCOMMON_H
#define UIFLOWWNDCOMMON_H

#include "UIFramework.h"

extern VControl UIFlowWndCommonCtrl;//Panel type 

extern VControl UIFlowWndCommon_TabHistogramCtrl;//Tab type 

typedef enum
{
UIFlowWndCommon_TabHistogram_MAX
}UIFlowWndCommon_TabHistogram_Setting;

//---------------------UIFlowWndCommonCtrl User Export---------------------------
#endif
