//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndCommonRes.c"
#include "UIFlowWndCommon.h"
#include "PrjCfg.h"

//---------------------UIFlowWndCommonCtrl Debug Definition -----------------------------
#define _UIFLOWWNDCOMMON_ERROR_MSG        1
#define _UIFLOWWNDCOMMON_TRACE_MSG        0

#if (_UIFLOWWNDCOMMON_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndCommonErrMsg(...)            debug_msg ("^R UIFlowWndCommon: "__VA_ARGS__)
#else
#define UIFlowWndCommonErrMsg(...)
#endif

#if (_UIFLOWWNDCOMMON_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndCommonTraceMsg(...)          debug_msg ("^B UIFlowWndCommon: "__VA_ARGS__)
#else
#define UIFlowWndCommonTraceMsg(...)
#endif

//---------------------UIFlowWndCommonCtrl Global Variables -----------------------------

//---------------------UIFlowWndCommonCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndCommonCtrl Public API  ----------------------------------

//---------------------UIFlowWndCommonCtrl Private API  ---------------------------------
//---------------------UIFlowWndCommonCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndCommon)
CTRL_LIST_ITEM(UIFlowWndCommon_TabHistogram)
CTRL_LIST_END

//----------------------UIFlowWndCommonCtrl Event---------------------------
INT32 UIFlowWndCommon_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndCommon_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndCommon)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndCommon_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndCommon_OnClose)
EVENT_END

INT32 UIFlowWndCommon_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndCommon_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndCommon_TabHistogramCtrl Event---------------------------
INT32 UIFlowWndCommon_TabHistogram_OnRedraw(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndCommon_TabHistogram)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWndCommon_TabHistogram_OnRedraw)
EVENT_END

INT32 UIFlowWndCommon_TabHistogram_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_REDRAW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
