//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndWrnStrgHotPlugRes.c"
#include "UIFlowWndWrnStrgHotPlug.h"
#include "PrjCfg.h"

//---------------------UIFlowWndWrnStrgHotPlugCtrl Debug Definition -----------------------------
#define _UIFLOWWNDWRNSTRGHOTPLUG_ERROR_MSG        1
#define _UIFLOWWNDWRNSTRGHOTPLUG_TRACE_MSG        0

#if (_UIFLOWWNDWRNSTRGHOTPLUG_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndWrnStrgHotPlugErrMsg(...)            debug_msg ("^R UIFlowWndWrnStrgHotPlug: "__VA_ARGS__)
#else
#define UIFlowWndWrnStrgHotPlugErrMsg(...)
#endif

#if (_UIFLOWWNDWRNSTRGHOTPLUG_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndWrnStrgHotPlugTraceMsg(...)          debug_msg ("^B UIFlowWndWrnStrgHotPlug: "__VA_ARGS__)
#else
#define UIFlowWndWrnStrgHotPlugTraceMsg(...)
#endif

//---------------------UIFlowWndWrnStrgHotPlugCtrl Global Variables -----------------------------

//---------------------UIFlowWndWrnStrgHotPlugCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndWrnStrgHotPlugCtrl Public API  ----------------------------------

//---------------------UIFlowWndWrnStrgHotPlugCtrl Private API  ---------------------------------
//---------------------UIFlowWndWrnStrgHotPlugCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndWrnStrgHotPlug)
CTRL_LIST_ITEM(UIFlowWndWrnStrgHotPlug_StatusTXT_Msg)
CTRL_LIST_END

//----------------------UIFlowWndWrnStrgHotPlugCtrl Event---------------------------
INT32 UIFlowWndWrnStrgHotPlug_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnStrgHotPlug_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnStrgHotPlug_OnRedraw(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnStrgHotPlug_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndWrnStrgHotPlug_OnTimer(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndWrnStrgHotPlug)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndWrnStrgHotPlug_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndWrnStrgHotPlug_OnClose)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWndWrnStrgHotPlug_OnRedraw)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndWrnStrgHotPlug_OnStorageChange)
EVENT_ITEM(NVTEVT_TIMER,UIFlowWndWrnStrgHotPlug_OnTimer)
EVENT_END

INT32 UIFlowWndWrnStrgHotPlug_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnStrgHotPlug_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnStrgHotPlug_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_REDRAW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnStrgHotPlug_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndWrnStrgHotPlug_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndWrnStrgHotPlug_StatusTXT_MsgCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndWrnStrgHotPlug_StatusTXT_Msg)
EVENT_END

