//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayQuickDelRes.c"
#include "UIMenuWndPlayQuickDel.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPlayQuickDelCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYQUICKDEL_ERROR_MSG        1
#define _UIMENUWNDPLAYQUICKDEL_TRACE_MSG        0

#if (_UIMENUWNDPLAYQUICKDEL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayQuickDelErrMsg(...)            debug_msg ("^R UIMenuWndPlayQuickDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayQuickDelErrMsg(...)
#endif

#if (_UIMENUWNDPLAYQUICKDEL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayQuickDelTraceMsg(...)          debug_msg ("^B UIMenuWndPlayQuickDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayQuickDelTraceMsg(...)
#endif

//---------------------UIMenuWndPlayQuickDelCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayQuickDelCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayQuickDelCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayQuickDelCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayQuickDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickDel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickDel_Status)
CTRL_LIST_ITEM(UIMenuWndPlayQuickDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickDelCtrl Event---------------------------
INT32 UIMenuWndPlayQuickDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayQuickDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayQuickDel_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayQuickDel_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayQuickDel_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayQuickDel_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlayQuickDel_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlayQuickDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayQuickDel_StatusCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickDel_Status)
EVENT_END

//---------------------UIMenuWndPlayQuickDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickDel_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayQuickDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayQuickDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayQuickDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayQuickDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayQuickDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayQuickDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
