//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlaySlideShowRes.c"
#include "UIMenuWndPlaySlideShow.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPlaySlideShowCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYSLIDESHOW_ERROR_MSG        1
#define _UIMENUWNDPLAYSLIDESHOW_TRACE_MSG        0

#if (_UIMENUWNDPLAYSLIDESHOW_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlaySlideShowErrMsg(...)            debug_msg ("^R UIMenuWndPlaySlideShow: "__VA_ARGS__)
#else
#define UIMenuWndPlaySlideShowErrMsg(...)
#endif

#if (_UIMENUWNDPLAYSLIDESHOW_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlaySlideShowTraceMsg(...)          debug_msg ("^B UIMenuWndPlaySlideShow: "__VA_ARGS__)
#else
#define UIMenuWndPlaySlideShowTraceMsg(...)
#endif

//---------------------UIMenuWndPlaySlideShowCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlaySlideShowCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlaySlideShowCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlaySlideShowCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlaySlideShowCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlaySlideShow)
CTRL_LIST_ITEM(UIMenuWndPlaySlideShow_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlaySlideShowCtrl Event---------------------------
INT32 UIMenuWndPlaySlideShow_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlaySlideShow)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlaySlideShow_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlaySlideShow_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlaySlideShow_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlaySlideShow_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlaySlideShow_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlaySlideShow_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlaySlideShow_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlaySlideShow_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlaySlideShow_Panel)
CTRL_LIST_ITEM(UIMenuWndPlaySlideShow_Menu)
CTRL_LIST_END

//----------------------UIMenuWndPlaySlideShow_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlaySlideShow_Panel)
EVENT_END

//----------------------UIMenuWndPlaySlideShow_MenuCtrl Event---------------------------
INT32 UIMenuWndPlaySlideShow_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlaySlideShow_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlaySlideShow_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlaySlideShow_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlaySlideShow_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlaySlideShow_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlaySlideShow_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlaySlideShow_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
