//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndPlayQuickConfirmDelRes.c"
#include "UIMenuWndPlayQuickConfirmDel.h"
#include "PrjCfg.h"

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Debug Definition -----------------------------
#define _UIMENUWNDPLAYQUICKCONFIRMDEL_ERROR_MSG        1
#define _UIMENUWNDPLAYQUICKCONFIRMDEL_TRACE_MSG        0

#if (_UIMENUWNDPLAYQUICKCONFIRMDEL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndPlayQuickConfirmDelErrMsg(...)            debug_msg ("^R UIMenuWndPlayQuickConfirmDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayQuickConfirmDelErrMsg(...)
#endif

#if (_UIMENUWNDPLAYQUICKCONFIRMDEL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndPlayQuickConfirmDelTraceMsg(...)          debug_msg ("^B UIMenuWndPlayQuickConfirmDel: "__VA_ARGS__)
#else
#define UIMenuWndPlayQuickConfirmDelTraceMsg(...)
#endif

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Global Variables -----------------------------

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Public API  ----------------------------------

//---------------------UIMenuWndPlayQuickConfirmDelCtrl Private API  ---------------------------------
//---------------------UIMenuWndPlayQuickConfirmDelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickConfirmDel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_Panel)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickConfirmDelCtrl Event---------------------------
INT32 UIMenuWndPlayQuickConfirmDel_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndPlayQuickConfirmDel_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndPlayQuickConfirmDel_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIMenuWndPlayQuickConfirmDel_OnChildClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndPlayQuickConfirmDel_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndPlayQuickConfirmDel_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndPlayQuickConfirmDel_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndPlayQuickConfirmDel_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndPlayQuickConfirmDel_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndPlayQuickConfirmDel_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndPlayQuickConfirmDel_Panel)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_Menu)
CTRL_LIST_ITEM(UIMenuWndPlayQuickConfirmDel_StatusText)
CTRL_LIST_END

//----------------------UIMenuWndPlayQuickConfirmDel_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_Panel)
EVENT_END

//----------------------UIMenuWndPlayQuickConfirmDel_MenuCtrl Event---------------------------
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_Menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter)
EVENT_END

INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndPlayQuickConfirmDel_Menu_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndPlayQuickConfirmDel_StatusTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndPlayQuickConfirmDel_StatusText)
EVENT_END

