//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPrintRes.c"
#include "UIFlowWndPrint.h"
#include "PrjCfg.h"

//---------------------UIFlowWndPrintCtrl Debug Definition -----------------------------
#define _UIFLOWWNDPRINT_ERROR_MSG        1
#define _UIFLOWWNDPRINT_TRACE_MSG        0

#if (_UIFLOWWNDPRINT_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndPrintErrMsg(...)            debug_msg ("^R UIFlowWndPrint: "__VA_ARGS__)
#else
#define UIFlowWndPrintErrMsg(...)
#endif

#if (_UIFLOWWNDPRINT_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndPrintTraceMsg(...)          debug_msg ("^B UIFlowWndPrint: "__VA_ARGS__)
#else
#define UIFlowWndPrintTraceMsg(...)
#endif

//---------------------UIFlowWndPrintCtrl Global Variables -----------------------------

//---------------------UIFlowWndPrintCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndPrintCtrl Public API  ----------------------------------

//---------------------UIFlowWndPrintCtrl Private API  ---------------------------------
//---------------------UIFlowWndPrintCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPrint)
CTRL_LIST_ITEM(UIFlowWndPrint_Panel)
CTRL_LIST_END

//----------------------UIFlowWndPrintCtrl Event---------------------------
INT32 UIFlowWndPrint_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPrint_OnPrintDpsEvent(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPrint)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPrint_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPrint_OnClose)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPrint_OnChildClose)
EVENT_ITEM(NVTEVT_CB_PRINT_DPS_EVENT,UIFlowWndPrint_OnPrintDpsEvent)
EVENT_END

INT32 UIFlowWndPrint_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPrint_OnPrintDpsEvent(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIFlowWndPrint_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPrint_Panel)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Icon_Static)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Text_Static)
CTRL_LIST_ITEM(UIFlowWndPrint_PicBridge_Status_Static)
CTRL_LIST_END

//----------------------UIFlowWndPrint_PanelCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_Panel)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Icon_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Icon_Static)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Text_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Text_Static)
EVENT_END

//----------------------UIFlowWndPrint_PicBridge_Status_StaticCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPrint_PicBridge_Status_Static)
EVENT_END

