//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDPRINT_H
#define UIFLOWWNDPRINT_H

#include "UIFramework.h"

extern VControl UIFlowWndPrintCtrl;//Panel type 

extern VControl UIFlowWndPrint_PanelCtrl;//Panel type 

extern VControl UIFlowWndPrint_PicBridge_Icon_StaticCtrl;//Status type 

typedef enum
{
UIFlowWndPrint_PicBridge_Icon_Static_ICON_PICTBRIDGE_S,
UIFlowWndPrint_PicBridge_Icon_Static_MAX
}UIFlowWndPrint_PicBridge_Icon_Static_Setting;

extern VControl UIFlowWndPrint_PicBridge_Text_StaticCtrl;//Static type 

extern VControl UIFlowWndPrint_PicBridge_Status_StaticCtrl;//Status type 

typedef enum
{
UIFlowWndPrint_PicBridge_Status_Static_STRID_PLEASE_WAIT,
UIFlowWndPrint_PicBridge_Status_Static_STRID_REMOVEUSBCABLE,
UIFlowWndPrint_PicBridge_Status_Static_MAX
}UIFlowWndPrint_PicBridge_Status_Static_Setting;

//---------------------UIFlowWndPrintCtrl User Export---------------------------
#endif
