//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCarNumConfirmRes.c"
#include "UIMenuWndSetupCarNumConfirm.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupCarNumConfirmCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPCARNUMCONFIRM_ERROR_MSG        1
#define _UIMENUWNDSETUPCARNUMCONFIRM_TRACE_MSG        0

#if (_UIMENUWNDSETUPCARNUMCONFIRM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupCarNumConfirmErrMsg(...)            debug_msg ("^R UIMenuWndSetupCarNumConfirm: "__VA_ARGS__)
#else
#define UIMenuWndSetupCarNumConfirmErrMsg(...)
#endif

#if (_UIMENUWNDSETUPCARNUMCONFIRM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupCarNumConfirmTraceMsg(...)          debug_msg ("^B UIMenuWndSetupCarNumConfirm: "__VA_ARGS__)
#else
#define UIMenuWndSetupCarNumConfirmTraceMsg(...)
#endif

//---------------------UIMenuWndSetupCarNumConfirmCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupCarNumConfirmCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCarNumConfirmCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCarNumConfirmCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCarNumConfirmCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCarNumConfirm)
CTRL_LIST_ITEM(UIMenuWndSetupCarNumConfirm_Panel)
CTRL_LIST_END

//----------------------UIMenuWndSetupCarNumConfirmCtrl Event---------------------------
INT32 UIMenuWndSetupCarNumConfirm_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNumConfirm_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNumConfirm_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNumConfirm)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCarNumConfirm_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCarNumConfirm_OnClose)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupCarNumConfirm_OnKeyMenu)
EVENT_END

INT32 UIMenuWndSetupCarNumConfirm_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNumConfirm_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNumConfirm_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//---------------------UIMenuWndSetupCarNumConfirm_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCarNumConfirm_Panel)
CTRL_LIST_ITEM(UIMenuWndSetupCarNumConfirm_menu)
CTRL_LIST_END

//----------------------UIMenuWndSetupCarNumConfirm_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNumConfirm_Panel)
EVENT_END

//----------------------UIMenuWndSetupCarNumConfirm_menuCtrl Event---------------------------
INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNumConfirm_menu)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCarNumConfirm_menu_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCarNumConfirm_menu_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupCarNumConfirm_menu_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNumConfirm_menu_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
