//This source code is generated by UI Designer Studio.

#ifndef UIMENUWNDSETUPCARNUM_H
#define UIMENUWNDSETUPCARNUM_H

#include "UIFramework.h"

extern VControl UIMenuWndSetupCarNumCtrl;//Panel type 

extern VControl UIMenuWndSetupCarNum_TabCtrl;//Tab type 

typedef enum
{
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_1,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_2,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_3,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_4,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_5,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_6,
UIMenuWndSetupCarNum_Tab_UIMenuWndSetupCarNum_7,
UIMenuWndSetupCarNum_Tab_MAX
}UIMenuWndSetupCarNum_Tab_Setting;

extern VControl UIMenuWndSetupCarNum_1Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_2Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_3Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_4Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_5Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_6Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_7Ctrl;//Button type 

extern VControl UIMenuWndSetupCarNum_StatusICON_INPUTTYPECtrl;//Status type 

typedef enum
{
UIMenuWndSetupCarNum_StatusICON_INPUTTYPE_ICON_ABC,
UIMenuWndSetupCarNum_StatusICON_INPUTTYPE_ICON_NUM,
UIMenuWndSetupCarNum_StatusICON_INPUTTYPE_MAX
}UIMenuWndSetupCarNum_StatusICON_INPUTTYPE_Setting;

//---------------------UIMenuWndSetupCarNumCtrl User Export---------------------------
#endif
