//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndTouchTest_CalRes.c"
#include "UIFlowWndTouchTest_Cal.h"
#include "PrjCfg.h"

//---------------------UIFlowWndTouchTest_CalCtrl Debug Definition -----------------------------
#define _UIFLOWWNDTOUCHTEST_CAL_ERROR_MSG        1
#define _UIFLOWWNDTOUCHTEST_CAL_TRACE_MSG        0

#if (_UIFLOWWNDTOUCHTEST_CAL_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIFlowWndTouchTest_CalErrMsg(...)            debug_msg ("^R UIFlowWndTouchTest_Cal: "__VA_ARGS__)
#else
#define UIFlowWndTouchTest_CalErrMsg(...)
#endif

#if (_UIFLOWWNDTOUCHTEST_CAL_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIFlowWndTouchTest_CalTraceMsg(...)          debug_msg ("^B UIFlowWndTouchTest_Cal: "__VA_ARGS__)
#else
#define UIFlowWndTouchTest_CalTraceMsg(...)
#endif

//---------------------UIFlowWndTouchTest_CalCtrl Global Variables -----------------------------

//---------------------UIFlowWndTouchTest_CalCtrl Prototype Declaration  -----------------------

//---------------------UIFlowWndTouchTest_CalCtrl Public API  ----------------------------------

//---------------------UIFlowWndTouchTest_CalCtrl Private API  ---------------------------------
//---------------------UIFlowWndTouchTest_CalCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndTouchTest_Cal)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Panel)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Static_TL)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Static_BR)
CTRL_LIST_ITEM(UIFlowTouchTest_Cal_Status)
CTRL_LIST_END

//----------------------UIFlowWndTouchTest_CalCtrl Event---------------------------
INT32 UIFlowWndTouchTest_Cal_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndTouchTest_Cal_OnClose(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndTouchTest_Cal)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndTouchTest_Cal_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndTouchTest_Cal_OnClose)
EVENT_END

INT32 UIFlowWndTouchTest_Cal_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndTouchTest_Cal_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//---------------------UIFlowTouchTest_Cal_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowTouchTest_Cal_Panel)
CTRL_LIST_END

//----------------------UIFlowTouchTest_Cal_PanelCtrl Event---------------------------
INT32 UIFlowTouchTest_Cal_Panel_OnTimer(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick(VControl *, UINT32, UINT32 *);
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowTouchTest_Cal_Panel)
EVENT_ITEM(NVTEVT_TIMER,UIFlowTouchTest_Cal_Panel_OnTimer)
EVENT_ITEM(NVTEVT_DOUBLECLICK,UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick)
EVENT_ITEM(NVTEVT_RELEASE,UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease)
EVENT_END

INT32 UIFlowTouchTest_Cal_Panel_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelDoubleClick(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowTouchTest_Cal_Panel_OnTouchPanelRelease(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIFlowTouchTest_Cal_Static_TLCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Static_TL)
EVENT_END

//----------------------UIFlowTouchTest_Cal_Static_BRCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Static_BR)
EVENT_END

//----------------------UIFlowTouchTest_Cal_StatusCtrl Event---------------------------
EVENT_BEGIN(UIFlowTouchTest_Cal_Status)
EVENT_END

