//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupLoaderVersionRes.c"
#include "UIMenuWndSetupLoaderVersion.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupLoaderVersionCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPLOADERVERSION_ERROR_MSG        1
#define _UIMENUWNDSETUPLOADERVERSION_TRACE_MSG        0

#if (_UIMENUWNDSETUPLOADERVERSION_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupLoaderVersionErrMsg(...)            debug_msg ("^R UIMenuWndSetupLoaderVersion: "__VA_ARGS__)
#else
#define UIMenuWndSetupLoaderVersionErrMsg(...)
#endif

#if (_UIMENUWNDSETUPLOADERVERSION_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupLoaderVersionTraceMsg(...)          debug_msg ("^B UIMenuWndSetupLoaderVersion: "__VA_ARGS__)
#else
#define UIMenuWndSetupLoaderVersionTraceMsg(...)
#endif

//---------------------UIMenuWndSetupLoaderVersionCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupLoaderVersionCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupLoaderVersionCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupLoaderVersionCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupLoaderVersionCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupLoaderVersion)
CTRL_LIST_ITEM(UIMenuSetupLoaderNameText)
CTRL_LIST_ITEM(UIMenuSetupFWNameText)
CTRL_LIST_ITEM(UIMenuSetupLoaderVersionText)
CTRL_LIST_ITEM(UIMenuSetupBuildDateText)
CTRL_LIST_ITEM(UIMenuSetupBuildTimeText)
CTRL_LIST_END

//----------------------UIMenuWndSetupLoaderVersionCtrl Event---------------------------
INT32 UIMenuWndSetupLoaderVersion_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupLoaderVersion_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupLoaderVersion)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupLoaderVersion_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupLoaderVersion_OnClose)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupLoaderVersion_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupLoaderVersion_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupLoaderVersion_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupLoaderVersion_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupLoaderVersion_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupLoaderVersion_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupLoaderVersion_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupLoaderVersion_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuSetupLoaderNameTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupLoaderNameText)
EVENT_END

//----------------------UIMenuSetupFWNameTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupFWNameText)
EVENT_END

//----------------------UIMenuSetupLoaderVersionTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupLoaderVersionText)
EVENT_END

//----------------------UIMenuSetupBuildDateTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupBuildDateText)
EVENT_END

//----------------------UIMenuSetupBuildTimeTextCtrl Event---------------------------
EVENT_BEGIN(UIMenuSetupBuildTimeText)
EVENT_END

