//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIMenuWndSetupCarNumRes.c"
#include "UIMenuWndSetupCarNum.h"
#include "PrjCfg.h"

//---------------------UIMenuWndSetupCarNumCtrl Debug Definition -----------------------------
#define _UIMENUWNDSETUPCARNUM_ERROR_MSG        1
#define _UIMENUWNDSETUPCARNUM_TRACE_MSG        0

#if (_UIMENUWNDSETUPCARNUM_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndSetupCarNumErrMsg(...)            debug_msg ("^R UIMenuWndSetupCarNum: "__VA_ARGS__)
#else
#define UIMenuWndSetupCarNumErrMsg(...)
#endif

#if (_UIMENUWNDSETUPCARNUM_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndSetupCarNumTraceMsg(...)          debug_msg ("^B UIMenuWndSetupCarNum: "__VA_ARGS__)
#else
#define UIMenuWndSetupCarNumTraceMsg(...)
#endif

//---------------------UIMenuWndSetupCarNumCtrl Global Variables -----------------------------

//---------------------UIMenuWndSetupCarNumCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndSetupCarNumCtrl Public API  ----------------------------------

//---------------------UIMenuWndSetupCarNumCtrl Private API  ---------------------------------
//---------------------UIMenuWndSetupCarNumCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndSetupCarNum)
CTRL_LIST_ITEM(UIMenuWndSetupCarNum_Tab)
CTRL_LIST_ITEM(UIMenuWndSetupCarNum_StatusICON_INPUTTYPE)
CTRL_LIST_END

//----------------------UIMenuWndSetupCarNumCtrl Event---------------------------
INT32 UIMenuWndSetupCarNum_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_OnKeyMenu(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_OnKeyShutter2(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNum)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIMenuWndSetupCarNum_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIMenuWndSetupCarNum_OnClose)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIMenuWndSetupCarNum_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_MENU,UIMenuWndSetupCarNum_OnKeyMenu)
EVENT_ITEM(NVTEVT_KEY_MODE,UIMenuWndSetupCarNum_OnKeyMode)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIMenuWndSetupCarNum_OnKeyShutter2)
EVENT_END

INT32 UIMenuWndSetupCarNum_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCarNum_TabCtrl Event---------------------------
INT32 UIMenuWndSetupCarNum_Tab_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_Tab_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_Tab_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndSetupCarNum_Tab_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndSetupCarNum_Tab)
EVENT_ITEM(NVTEVT_KEY_UP,UIMenuWndSetupCarNum_Tab_OnKeyUp)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIMenuWndSetupCarNum_Tab_OnKeyDown)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIMenuWndSetupCarNum_Tab_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndSetupCarNum_Tab_OnKeyRight)
EVENT_END

INT32 UIMenuWndSetupCarNum_Tab_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_Tab_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_Tab_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_PREVIOUS_ITEM,0);
    return NVTEVT_CONSUME;
}
INT32 UIMenuWndSetupCarNum_Tab_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIMenuWndSetupCarNum_1Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_1)
EVENT_END

//----------------------UIMenuWndSetupCarNum_2Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_2)
EVENT_END

//----------------------UIMenuWndSetupCarNum_3Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_3)
EVENT_END

//----------------------UIMenuWndSetupCarNum_4Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_4)
EVENT_END

//----------------------UIMenuWndSetupCarNum_5Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_5)
EVENT_END

//----------------------UIMenuWndSetupCarNum_6Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_6)
EVENT_END

//----------------------UIMenuWndSetupCarNum_7Ctrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_7)
EVENT_END

//----------------------UIMenuWndSetupCarNum_StatusICON_INPUTTYPECtrl Event---------------------------
EVENT_BEGIN(UIMenuWndSetupCarNum_StatusICON_INPUTTYPE)
EVENT_END

